fix(GH-actions): add Debug Environment step

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -18,6 +18,11 @@ jobs:
         uses: pnpm/action-setup@v4
         with:
           version: 10
+      - name: Debug Environment
+        run: |
+          which pnpm || echo "pnpm not found"
+          echo "PATH: $PATH"
+          pnpm --version || echo "pnpm is not installed"
       - name: Install dependencies # Install dependencies.
         run: pnpm install
       - name: Run tests # Run tests
